version: 1.0.6
services:
  SO:
    image: docker.io/library/ubuntu
    container_name: prueba_sin_db_2_os_ubuntu
    volumes:
      - ./working_directory:/working_directory
      - ./code:/code
    working_dir: /working_directory
    command: >-
      /bin/bash -c "apt-get update && apt-get install -y git && git init && git
      config --global user.email 'you@example.com' && git config --global
      user.name 'exampÄºe' && sleep infinity"
    tty: true
